progress-bar component added
mobilelive-inc/friday-design-system pull request #95
Opened 2021-04-14 19:17 UTC by Hamza-Rafique

# Description
## Jira Issue: 

# Notes / Caveats

# Testing/Usage 

# Regression Risks

# Design/Product Sign-Off

# Demo

2021-04-16 20:23 UTC, zeenainali commented on apps/rx-xis-app/src/components/progress/index.js
> +            className="btn btn-primary"
Why we are not using pros instead of using class and also include button component here.

2021-04-16 20:26 UTC, zeenainali commented on yarn.lock
> +postcss-calc@^8.0.0:
Why we are using PostCss for React

2021-04-16 20:29 UTC, Hamza-Rafique commented
i forgot to remove className, here no work of className. I already use  the
button component.

*Hamza Rafique*

Software Engineer




On Sat, Apr 17, 2021 at 1:23 AM Zulqarnain Ali ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In apps/rx-xis-app/src/components/progress/index.js
> <https://github.com/mobilelive-inc/friday-design-system/pull/95#discussion_r615103527>
> :
>
> > +        <Progresbar
> +          role="progressbar"
> +          aria-valuenow="3"
> +          aria-valuemin="0"
> +          aria-valuemax="10"
> +          aria-label={style}
> +        >
> +          <Value style={style}></Value>
> +        </Progresbar>
> +        <Text variant="h3" mt={5} ml={25}>
> +          ({`${progress}`} of 10)
> +        </Text>
> +        <br />
> +        <ButtonContainer>
> +          <Button
> +            className="btn btn-primary"
>
> Why we are not using pros instead of using class and also include button
> component here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mobilelive-inc/friday-design-system/pull/95#pullrequestreview-638059944>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALHOVP4M6PFTPVE3EXRBT7TTJCMFNANCNFSM42574RFA>
> .
>

2021-04-20 22:22 UTC, zeenainali requested changes

2021-04-20 22:22 UTC, zeenainali commented on apps/rx-xis-app/src/components/cards/css.js
> +    border: `4px solid`,
border size should be from theme file

2021-04-20 22:22 UTC, zeenainali commented on apps/rx-xis-app/src/components/cards/css.js
> +    border: "2px solid",
this one too.

2021-04-20 22:22 UTC, zeenainali commented on apps/rx-xis-app/src/components/cards/css.js
> +    boxShadow: "5px 10px",
this should be from theme file

2021-04-20 22:22 UTC, zeenainali commented on apps/rx-xis-app/src/components/cards/css.js
> +    width: "732px",
Why fixed width

2021-05-21 10:20 UTC, merged